### ISSUE TITLE
[Bug] Getting error when using Postgres and generating migration

### ISSUE THREAD

**Issue by luchillo17** [typeorm/typescript-express-example#2]
After downloading, installing and adding `pg` package, i created a database and run this: `typeorm migrations:generate -n seller` and the result is this:
![image](https://user-images.githubusercontent.com/9698639/28483483-1f2621f0-6e33-11e7-8cfd-a336ff2e2fbe.png)

The only change i made was the connection args and the installation of postgres.

Any idea why this error?

**Comment by pleerock** [comment]
@luchillo17 do you still have this issue?

**Comment by luchillo17** [comment]
Dunno, let me try.

I remember have used it before for another migration, now it works fine, though i had to adjust the command a bit with `ts-node` and connection name:
![image](https://user-images.githubusercontent.com/9698639/30813277-9a0a6d36-a1d2-11e7-94f4-583624e8e0c2.png)

But i tried with mine, not with the example repo.
