### ISSUE TITLE
What is the best way to test this?

### ISSUE THREAD

**Issue by Kogs** [typeorm/typescript-express-example#6]
I'm wondering how to write tests for this kind of express/typorm project setup.

How to mock the Repositories? 

Any ideas/recommendations?

**Comment by oliviergf** [comment]
good question^

**Comment by Kogs** [comment]
It's not testable like that. What I did was writing 'business objects' that use internally TypeOrm Repositories. This BO classes then can get mocked so there is no database connection required.
