### ISSUE TITLE
Is this concurrency-safe?

### ISSUE THREAD

**Issue by yang** [typeorm/typescript-express-example#7]
You have a single `createConnection()` happening once at the top of this example.  I understand that creates a connection pool.  But how does TypeORM when it should add vs reuse connections in the pool?  (If you have two requests coming in at the same time, and each request handler makes some queries, how does TypeORM know which queries go to which connection?)

**Comment by yang** [comment]
Moving this discussion to https://github.com/typeorm/typeorm/issues/2581

**Comment by pleerock** [comment]
Answered in there.
